services:
  app:
    image: ghcr.io/foowy/learning_languages:latest
    ports:
      - "13200:13200"
    volumes:
      - /mnt/secdrive/docker/data/japanese-learning:/data
      - /mnt/secdrive/docker/config/japanese-learning:/config
    restart: unless-stopped
    environment:
      - DATA_DIR=/data
      - CONFIG_DIR=/config
      - PORT=13200
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
